pipeline:

  frontend:
    image: node:10.15.3-alpine
    commands:
    - npm install
    when:
      event: pull_request
    
  scan:
    image: snyk/snyk-cli:npm
    commands:
    - echo  ${SNYK_TOKEN}
    - PROJECT_FOLDER=/drone/src/.git snyk test --json | jq .vulnerabilities
    - PROJECT_FOLDER=/drone/src/.git snyk monitor --json |  jq -r .uri
    secrets: [snyk_token]
    when:
      event: pull_request

  comment-pr:
    image: gboo/github-pr
    secrets: [ github_token ]
    action: comment
    message: "This PR looks good so far!"
    when:
      event: pull_request

  merge-pr:
    image: gboo/github-pr
    secrets: [ github_token ]
    action: rebase
    message: "Merging this PR"
    when:
      event: pull_request
