# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI
  
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Run K8s Deployment
      uses: stefanprodan/kube-tools@v1
      with:
        kubectl: 1.18.0
        kustomize: 3.4.0
        helm: 2.16.5
        helmv3: 3.1.2
        command: |
          echo "Run conftest"
          kubectl version
          echo ${{secrets.STG_K8S_KC}}
          mkdir ~/.kube
          ls -lrt  ~/.kube/config
          cd ~/.kube/config
          pwd 
          kubectl get nodes --kubeconfig=~/.kube/config
